### ISSUE TITLE
Respect private browsing mode

### ISSUE THREAD

**Issue by daviddahl** [mozilla/cookiemonster#12]
Ignore any cookies set in browsing mode

**Comment by daviddahl** [comment]
Not sure how this has changed with per-window-private-browsing

**Comment by daviddahl** [comment]
Currently, we are still collecting cookie data in PBM. I imagine we might be able to get the tab or window context via the nsIChannel and determine if PBM is active for that channel/tab/window and ignore it

**Comment by daviddahl** [comment]
this is easy http://mxr.mozilla.org/mozilla-central/source/netwerk/base/public/nsIPrivateBrowsingChannel.idl#15

**Comment by monicachew** [comment]
Fixed by #22
