### ISSUE TITLE
document the stats that we want to collect

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#16]
put it in doc as a Markdown
1. Stats that we collect
2. Stats that we want to collect
3. Stats that require a closer look at privacy
4. Options for sending data back
5. Time estimates for using micropilot alone, embedding with test pilot, or just contributing to collusion

**Comment by monicachew** [comment]
One question we want to answer: who are the trackers? Can we verify Evidon's work?
http://adage.com/article/dataworks/grabbing-consumer-data-publishers

**Comment by daviddahl** [comment]
Getting a 404 on that link

**Comment by monicachew** [comment]
That's what I get for trying to strip URLs 
http://adage.com/article/dataworks/grabbing-consumer-data-publishers/240295/ 

----- Original Message -----

**Comment by monicachew** [comment]
Done in designdoc.md
