### ISSUE TITLE
count accepted/rejected cookies

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#17]
Observing nsICookieManager should give us this

**Comment by daviddahl** [comment]
do we want to just keep a running total here (in case of rejected cookies)? or do we want to track it like:

{ eventType: 'rejected', domain: 'foo.com', referrer: "baz.com", timestamp: 123456789 } 

In the case of 'accepted' cookies, is this a case where the user has to manually approve all cookies, or an extension is doing the thinking on what to accept?

**Comment by monicachew** [comment]
I think we want more than the running count. In the case of accept, I don't think we can tell why it was accepted.

**Comment by monicachew** [comment]
This is done.
