### ISSUE TITLE
Keep track of top N domains only

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#2]
Right now the code is prone to memory explosion. Keep track of the top N domains only.

**Comment by daviddahl** [comment]
Top 100 Alexa or other list?

**Comment by daviddahl** [comment]
Looks like the top 1000 would be better

**Comment by monicachew** [comment]
I'm wondering if the current code is doing the aggregation in the wrong place. micropilot/testpilot idioms seem to be to log events back to the data collector. If we're using collusion file format and keeping the whole cookie then it doesn't save us any space to aggregate client side as well.

**Comment by monicachew** [comment]
Obsolete, we're logging every event.
