### ISSUE TITLE
Keep track of when cookies are cleared by the user and for what domains, if possible

### ISSUE THREAD

**Issue by daviddahl** [mozilla/cookiemonster#20]
I am not sure if there is a notification that will give us all of this data, probably not, in which case we can just keep track of the number of manual "cookie clear" events.

**Comment by monicachew** [comment]
We can at least keep track of clear private data settings (there are a bunch of prefs that reflect this) 

----- Original Message -----

**Comment by monicachew** [comment]
Done and tested
