### ISSUE TITLE
can we make a graph of "superconnected" sites?

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#21]
I love the superconnected companies graph from this paper:
http://arxiv.org/PS_cache/arxiv/pdf/1107/1107.5728v2.pdf

I wonder if domain/referrer relationships could represent links in a similar graph, or (more likely) we'd have to pay attention to js script inclusions since I bet very few people visit say, doubleclick.net in a first party context.

**Comment by monicachew** [comment]
This link is probably more canonical: http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0025995

**Comment by daviddahl** [comment]
Ah. I know of this paper. Nice idea.
