### ISSUE TITLE
Monitor and record social widget usage

### ISSUE THREAD

**Issue by daviddahl** [mozilla/cookiemonster#23]
2 things here:
1. monitor HTTP connections, checking for facebook and twitter share requests
2. record these events / resulting cookies? etc?

**Comment by monicachew** [comment]
I think we're ok on cookies, since we've already got domain information in the cookie events. But yes to 1! :)

**Comment by daviddahl** [comment]
Some urls to monitor: 
http://www.facebook.com/sharer/sharer.php
https://twitter.com/intent/tweet

what other urls?

**Comment by daviddahl** [comment]
Fixed in pull request 36 - also partially supports G+
