### ISSUE TITLE
Check nsiCookieService.canAccess

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#27]

**Comment by monicachew** [comment]
Here's an alternative implementation which may be easier. We are logging all set-cookie requests -- whether or not a given request is accepted depends on the cookie exception list, which no one uses, and the preference network.cookie.cookieBehavior. We can include Services.cookiemgr.countCookiesFromHost(uri.host) as a field in the set request, which may be more reliable than munging on the channel, and might be more interesting anyway.

So we can still make the graphs:
1) Set cookie requests by domain
2) Set cookie requests by first party, third party pairs
3) Set cookie requests that would be accepted/rejected if the user's preference is "accept first party only", "accept_third_party_from_visited"

Btw, we are already counting "cookie-changed", "cookie-added" and "cookie-deleted" events as well.

**Comment by daviddahl** [comment]
I gave up on this, using monica's "Services.cookiemgr.countCookiesFromHost(uri.host) "
