### ISSUE TITLE
Identify login cookies

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#3]
There are a small handful that are interesting.

**Comment by monicachew** [comment]
Not login cookies, but may be worth profiling: https://developers.google.com/analytics/devguides/collection/gajs/cookie-usage

GAPS and PREF cookie, same thing: http://ashkansoltani.org/docs/google_safe_browsing.html
http://googleblog.blogspot.com/2007/07/cookies-expiring-sooner-to-improve.html

Google LSID, SID, other auth cookies?

Facebook datr cookie and friends: http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&ved=0CD4QFjAC&url=http%3A%2F%2Fdragon.ak.fbcdn.net%2Fcfs-ak-snc6%2F84992%2F979%2F395701387118444_1090193793.pdf&ei=GcMaUeDlKqScjALQ2YGQBQ&usg=AFQjCNEz3hVzl7cAht6XzW2eWI0Z1sBNpA&bvm=bv.42261806,d.cGE

Rough guide (?!) has a nice overview of these: http://www.roughguides.com/privacy-cookies/

**Comment by daviddahl** [comment]
So, do we want an algorithm that is used to identify login cookies on any site, or are we interested in flagging/counting logins from each site mentioned in the Rough Guide privacy page? Or is there another bit of functionality we need?

**Comment by daviddahl** [comment]
We need to ID login cookies for Google, Facebook, Twitter, Yahoo

We need save these _events_ in another object of some kind: what does this look like?

**Comment by daviddahl** [comment]
4 counts: # times visit to the site, 3rd party cookie sets and gets, # times social widget is used
