### ISSUE TITLE
keep track of cookie lifetimes

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#4]
Would be interesting to get the distribution on this, and if there are any legitimate sites that need a cookie lifetime longer than 3 months or so.

**Comment by monicachew** [comment]
Cookies come with expiration dates. How many sites are abusing "never expire"? Are these sites that people visit on a first party basis

If you haven't visited the site in X days, do you still want to keep the cookie?

**Comment by daviddahl** [comment]
2 questions: what do we consider "legitimate sites"? how far in the future is the expiration that we consider a cookie as a "never-expire" cookie?

**Comment by monicachew** [comment]
The first is an open question. I think that visiting a site or interacting with a widget that belongs to it grants a certain air of legitimacy.

For 2., I saw so many cookies based on issue #10 that had longer than a year expiration. I would guess that many people reinstall, clear cookies entirely, or get a new device within a similar timeframe -- so these are essentially equivalent to "never-expire." Needs more research though.

**Comment by monicachew** [comment]
Fixed.
