### ISSUE TITLE
prep for inclusion in user-action unified study

### ISSUE THREAD

**Issue by gregglind** [mozilla/cookiemonster#42]
Many points:
- split in to main, and cookiemonster.js
- 'emit' to a `sdk/system/events` channel
- add a `group:"cookiemonster"`, tabid?  To make it consistent.

**Comment by monicachew** [comment]
Also, flagify and turn off by default all events but set-cookie.

**Comment by daviddahl** [comment]
I have merged the new-instrumentation branch and I think updated the code to llok like gregglind's latest pull request. The xpi is working as expected as an XPI.

gregglind: does this work for you?

**Comment by monicachew** [comment]
This is done.
