### ISSUE TITLE
recordPrefs() not called in production

### ISSUE THREAD

**Issue by daviddahl** [mozilla/cookiemonster#47]
Looks like our recordPrefs() function is not actually called in production. The metadata we get for each user session does not include the prefs we wanted to track.

Here is what we get, other than 'events':
{<events: [...],
u'personid': u'1180268597',
 u'ts': 1370937594070,
 u'uploadid': u'c0e3ee0d-5dda-4c6e-ab3d-5936ba2c67b9'}

Somehow, we do not call recordPrefs() when an upload happens, perhaps that has to be triggered from gregg's code?

**Comment by daviddahl** [comment]
we need greg's code to call recordPrefs() and add a 'preferences' property to each user session as it is uploaded. We will be missing some key metrics we want to report on without this data

**Comment by daviddahl** [comment]
After chatting with gregg, it looks like the data is captured, but the sample I have is not complete. Leaving this bug open for now.

**Comment by monicachew** [comment]
Yes, because we're not calling our own upload function in production, only when we're standalone. The heatmap survey listens to the system events we emit and then dumps prefs on upload, similar to what our standalone thing does.

Do we have a complete sample yet?

**Comment by daviddahl** [comment]
no complete sample yet. The data we have is a "slice", I think its about 1 million events, not just our own. So this leads me to believe that we are not capturing prefs after all. Gregg said we are last week in irc.

**Comment by monicachew** [comment]
I think it might be ok. If we're not seeing the upload event, it makes sense we wouldn't be seeing prefs. 

----- Original Message -----
