### ISSUE TITLE
look at collusion file format

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#5]
https://github.com/mozilla/collusion/blob/master/doc/file_format.md

**Comment by daviddahl** [comment]
After looking at the Version 1.0 collusion file format, it would seem like we can build our report data from it quite easily. The only problem I have is data storage. I would hate to keep too much data in memory for days on end. 

I think we can solve this by using the chrome IndexedDB API which allows unlimited storage. We would only need to read all of the data when we push to the server. All of the new web apis use IndexedDB like this

**Comment by daviddahl** [comment]
Update: the latest file format for Collusion is v1.1: https://github.com/mozilla/collusion/blob/c2_fresh_start/doc/data_format.v1.1.md

Even with all of the data being collected, the performance is good just using simple-storage, so perhaps an indexedDB-approach is too heavy handed.

**Comment by monicachew** [comment]
OK, I think Dethe may have come to similar conclusions (search for simple-storage in https://etherpad.mozilla.org/collusionweekly)

We should probably get together and chat at some point.

**Comment by monicachew** [comment]
We decided not to use this.
