### ISSUE TITLE
look at micropilot

### ISSUE THREAD

**Issue by monicachew** [mozilla/cookiemonster#6]
https://github.com/gregglind/micropilot

Supposedly this can send back data in a lightweight way.

**Comment by monicachew** [comment]
I talked to Gregg this morning, and the answer is definitely "use micropilot". This is basically next-gen testpilot. The new model will be
1. testpilot in m-c will be stripped down to something that only knows how to install addons and set a timer
2. TP studies will be: implement an addon using micropilot to do all your own instrumentation and collection (up to 160 messages/minute, using indexeddb)
3. After some time testpilot in m-c can check to see if a study should be removed, or disable badly behaved studies, etc.

Re: who can receive data, the answer is anyone who can receive HTTP post requests. The current default URL points back to a DC owned by metrics team that we (and Gregg) can't easily access, so we probably shouldn't use it. The data comes back as JSON.

The instructions under the README (https://github.com/gregglind/micropilot#install) look pretty accurate and we should try it out. volo is intended to keep dependencies (micropilot would be one of cookiemonster) up to date more easily, instead of manually cloning into our own repo, etc.

I might try to check this out over the weekend, if the weather isn't too beautiful.

**Comment by monicachew** [comment]
Re: collecting URLS, Gregg says that they have done, before. That does not mean that we can skip our due diligence though.

**Comment by daviddahl** [comment]
I think it would be viewed as an invasion of privacy if we cataloged folks browsing habits on a scale like this. We should probably figure out how to obfuscate the domians - even then, say with a hash - we would also have to hash the cookie names.

EDIT: nevermind, we are only collecting domains, not urls:)

**Comment by daviddahl** [comment]
Attempting to integrate with MicroPilot. The upload "Fuse" timer does not work for me. See https://github.com/mozilla/cookiemonster/commit/78967b4dd05f453759fbd13aac64a90a17375c50

**Comment by monicachew** [comment]
It is working for me, with this in my lib/main.js

const { storage } = require("simple-storage");
if (!storage.lastUpload) {
  storage.lastUpload = Date.now();
  console.log("Set last upload");
}

let micropilot = require("micropilot");

let monitor = micropilot.Micropilot('tapopenstudy').start();
var tabs = require('tabs');
tabs.on('ready', function () {
  monitor.record({'msg': 'tab ready', 'ts': Date.now()});
});

monitor.record({"key": "value"});
//monitor.upload("fake.com", { simulate: true }).then(function(request) {
//  console.log(JSON.stringify(request.content));
//});

daily_upload = function _daily_upload() {
  console.log("Fuse triggering");
  storage.lastupload = Date.now();
  monitor.record({"uploading": storage.lastupload});
  monitor.upload("fake.com", { simulate: true }).then(function(req) {
    console.log(JSON.stringify(req.content));
  });
};

final_upload = function _final_upload() {
  console.log("Fuse blowing");
  // Dump all prefs
  monitor.upload("fake.com", { simulate: true }).then(function(req) {
    console.log(JSON.stringify(req.content));
  });
};

micropilot.Fuse({
  start: storage.lastupload,
  duration: 60 \* 1000, /\* 10 sec */
  pulseinterval: 10 \* 1000,
  pulsefn: daily_upload
}).then(final_upload);

**Comment by daviddahl** [comment]
does the 'duration' govern when the 'final upload' takes place? I was trying to get the 'final_upload' to pulse. Perhaps I read the docs wrong. Sigh.

**Comment by monicachew** [comment]
Yes, it does. Are you getting a stack trace?

**Comment by daviddahl** [comment]
Its working now, thanks for the testing!

**Comment by monicachew** [comment]
Fixed by issue #22
